Ext.define('SCE.store.HindiPTElements', {
	extend: 'Ext.data.Store',

	requires: ['SCE.model.PTElement'],

	model: 'SCE.model.PTElement',

	storeId: 'HindiPTElements',
	data: [
	{ z: '1', mass: null, symbol: 'H',name: 'हाइड्रोजन', group: 'Other Non-metals', row: 1, column: 1 },
	{ z: '2', mass: null, symbol: 'He',name: 'हिलियम', group: 'Nobel Gases', row: 1, column: 18 },
	{ z: '3', mass: null, symbol: 'Li',name: 'लिथियम', group: 'Alkali Metals', row: 2, column: 1 },
	{ z: '4', mass: null, symbol: 'Be',name: 'बेरिलियम', group: 'Alkali-Earth Metals', row: 2, column: 2 },
	{ z: '5', mass: null, symbol: 'B',name: 'बोरॉन', group: 'Semi Metals', row: 2, column: 13 },
	{ z: '6', mass: null, symbol: 'C',name: 'कार्बन', group: 'Non-Metals', row: 2, column: 14 },
	{ z: '7', mass: null, symbol: 'N',name: 'नाइट्रोजन', group: 'Non-Metals', row: 2, column: 15 },
	{ z: '8', mass: null, symbol: 'O',name: 'ऑक्सीजन', group: 'Non-Metals', row: 2, column: 16 },
	{ z: '9', mass: null, symbol: 'F',name: 'फ्लोरीन', group: 'Non-Metals', row: 2, column: 17 },
	{ z: '10', mass: null, symbol: 'Ne',name: 'नियोन', group: 'Nobel Gases', row: 2, column: 18 },
	{ z: '11', mass: null, symbol: 'Na',name: 'सोडियम', group: 'Alkali Metals', row: 3, column: 1 },
	{ z: '12', mass: null, symbol: 'Mg',name: 'मैग्नेशियम', group: 'Alkali-Earth Metals', row: 3, column: 2 },
	{ z: '13', mass: null, symbol: 'Al',name: 'एल्युमिनियम', group: 'Poor Metals', row: 3, column: 13 },
	{ z: '14', mass: null, symbol: 'Si',name: 'सिलिकॉन', group: 'Semi Metals', row: 3, column: 14 },
	{ z: '15', mass: null, symbol: 'P',name: 'फास्फोरस', group: 'Non-Metals', row: 3, column: 15 },
	{ z: '16', mass: null, symbol: 'S',name: 'गन्धक', group: 'Non-Metals', row: 3, column: 16 },
	{ z: '17', mass: null, symbol: 'Cl',name: 'क्लोरीन', group: 'Non-Metals', row: 3, column: 17 },
	{ z: '18', mass: null, symbol: 'Ar',name: 'ऑर्गन', group: 'Nobel Gases', row: 3, column: 18 },
	{ z: '19', mass: null, symbol: 'K',name: 'पोटैशियम', group: 'Alkali Metals', row: 4, column: 1 },
	{ z: '20', mass: null, symbol: 'Ca',name: 'कैल्शियम', group: 'Alkali-Earth Metals', row: 4, column: 2 },
	{ z: '21', mass: null, symbol: 'Sc',name: 'स्काण्डियम', group: 'Transition Metals', row: 4, column: 3 },
	{ z: '22', mass: null, symbol: 'Ti',name: 'टाइटानियम', group: 'Transition Metals', row: 4, column: 4 },
	{ z: '23', mass: null, symbol: 'V',name: 'वनेडियम', group: 'Transition Metals', row: 4, column: 5 },
	{ z: '24', mass: null, symbol: 'Cr',name: 'क्रोमियम', group: 'Transition Metals', row: 4, column: 6 },
	{ z: '25', mass: null, symbol: 'Mn',name: 'मैंगनीज', group: 'Transition Metals', row: 4, column: 7 },
	{ z: '26', mass: null, symbol: 'Fe',name: 'लोहा', group: 'Transition Metals', row: 4, column: 8 },
	{ z: '27', mass: null, symbol: 'Co',name: 'कोबाल्ट', group: 'Transition Metals', row: 4, column: 9 },
	{ z: '28', mass: null, symbol: 'Ni',name: 'निकेल', group: 'Transition Metals', row: 4, column: 10 },
	{ z: '29', mass: null, symbol: 'Cu',name: 'ताम्र', group: 'Transition Metals', row: 4, column: 11 },
	{ z: '30', mass: null, symbol: 'Zn',name: 'जस्ता', group: 'Transition Metals', row: 4, column: 12 },
	{ z: '31', mass: null, symbol: 'Ga',name: 'गैलियम', group: 'Poor Metals', row: 4, column: 13 },
	{ z: '32', mass: null, symbol: 'Ge',name: 'जर्मेनियम', group: 'Semi Metals', row: 4, column: 14 },
	{ z: '33', mass: null, symbol: 'As',name: 'आर्सेनिक', group: 'Semi Metals', row: 4, column: 15 },
	{ z: '34', mass: null, symbol: 'Se',name: 'सेलेनियम', group: 'Semi Metals', row: 4, column: 16 },
	{ z: '35', mass: null, symbol: 'Br',name: 'ब्रोमिन', group: 'Non-Metals', row: 4, column: 17 },
	{ z: '36', mass: null, symbol: 'Kr',name: 'क्रिप्टन', group: 'Nobel Gases', row: 4, column: 18 },
	{ z: '37', mass: null, symbol: 'Rb',name: 'रुबिडियम', group: 'Alkali Metals', row: 5, column: 1 },
	{ z: '38', mass: null, symbol: 'Sr',name: 'स्ट्रोन्सियम', group: 'Alkali-Earth Metals', row: 5, column: 2 },
	{ z: '39', mass: null, symbol: 'Y',name: 'इत्रियम', group: 'Transition Metals', row: 5, column: 3 },
	{ z: '40', mass: null, symbol: 'Zr',name: 'जर्कोनियम', group: 'Transition Metals', row: 5, column: 4 },
	{ z: '41', mass: null, symbol: 'Nb',name: 'नायोबियम', group: 'Transition Metals', row: 5, column: 5 },
	{ z: '42', mass: null, symbol: 'Mo',name: 'मोलिब्डेनम', group: 'Transition Metals', row: 5, column: 6 },
	{ z: '43', mass: null, symbol: 'Tc',name: 'टेक्निशियम', group: 'Transition Metals', row: 5, column: 7 },
	{ z: '44', mass: null, symbol: 'Ru',name: 'रुथेनियम', group: 'Transition Metals', row: 5, column: 8 },
	{ z: '45', mass: null, symbol: 'Rh',name: 'रोडियम', group: 'Transition Metals', row: 5, column: 9 },
	{ z: '46', mass: null, symbol: 'Pd',name: 'पलाडियम', group: 'Transition Metals', row: 5, column: 10 },
	{ z: '47', mass: null, symbol: 'Ag',name: 'चाँदी', group: 'Transition Metals', row: 5, column: 11 },
	{ z: '48', mass: null, symbol: 'Cd',name: 'काडमियम', group: 'Transition Metals', row: 5, column: 12 },
	{ z: '49', mass: null, symbol: 'In',name: 'इण्डियम', group: 'Poor Metals', row: 5, column: 13 },
	{ z: '50', mass: null, symbol: 'Sn',name: 'त्रपु', group: 'Poor Metals', row: 5, column: 14 },
	{ z: '51', mass: null, symbol: 'Sb',name: 'एन्टिमोनी', group: 'Semi Metals', row: 5, column: 15 },
	{ z: '52', mass: null, symbol: 'Te',name: 'टेलुरियम', group: 'Semi Metals', row: 5, column: 16 },
	{ z: '53', mass: null, symbol: 'I',name: 'आयोडिन', group: 'Non-Metals', row: 5, column: 17 },
	{ z: '54', mass: null, symbol: 'Xe',name: 'ज़ेनान', group: 'Nobel Gases', row: 5, column: 18 },
	{ z: '55', mass: null, symbol: 'Cs',name: 'सीज़ियम', group: 'Alkali Metals', row: 6, column: 1 },
	{ z: '56', mass: null, symbol: 'Ba',name: 'बेरियम', group: 'Alkali-Earth Metals', row: 6, column: 2 },
	{ z: '57-71', mass: null, symbol: 'La-Lu',name: 'Lanthanide', group: 'Lanthanides', row: 6, column: 3,
		items: [
			{ z: '57', mass: null, symbol: 'La',name: 'लाञ्थनम', group: 'Lanthanides', row: 1, column: 1 },
			{ z: '58', mass: null, symbol: 'Ce',name: 'सेरियम', group: 'Lanthanides', row: 1, column: 2 },
			{ z: '59', mass: null, symbol: 'Pr',name: 'प्रासियोडाइमियम', group: 'Lanthanides', row: 1, column: 3 },
			{ z: '60', mass: null, symbol: 'Nd',name: 'नियोडाइमियम', group: 'Lanthanides', row: 1, column: 4 },
			{ z: '61', mass: null, symbol: 'Pm',name: 'प्रोमेथियम', group: 'Lanthanides', row: 1, column: 5 },
			{ z: '62', mass: null, symbol: 'Sm',name: 'सैमरियम', group: 'Lanthanides', row: 1, column: 6 },
			{ z: '63', mass: null, symbol: 'Eu',name: 'युरोपियम', group: 'Lanthanides', row: 1, column: 7 },
			{ z: '64', mass: null, symbol: 'Gd',name: 'ग्याडोलिनियम', group: 'Lanthanides', row: 1, column: 8 },
			{ z: '65', mass: null, symbol: 'Tb',name: 'टर्बियम', group: 'Lanthanides', row: 1, column: 9 },
			{ z: '66', mass: null, symbol: 'Dy',name: 'डिस्प्रोसियम', group: 'Lanthanides', row: 1, column: 10 },
			{ z: '67', mass: null, symbol: 'Ho',name: 'होल्मियम', group: 'Lanthanides', row: 1, column: 11 },
			{ z: '68', mass: null, symbol: 'Er',name: 'अर्बियम', group: 'Lanthanides', row: 1, column: 12 },
			{ z: '69', mass: null, symbol: 'Tm',name: 'थुलियम', group: 'Lanthanides', row: 1, column: 13 },
			{ z: '70', mass: null, symbol: 'Yb',name: 'यिट्टरबियम', group: 'Lanthanides', row: 1, column: 14 },
			{ z: '71', mass: null, symbol: 'Lu',name: 'लुटेटियम', group: 'Lanthanides', row: 1, column: 15 }
		]
	},
	{ z: '72', mass: null, symbol: 'Hf',name: 'हाफ्नियम', group: 'Transition Metals', row: 6, column: 4 },
	{ z: '73', mass: null, symbol: 'Ta',name: 'टाण्टलम', group: 'Transition Metals', row: 6, column: 5 },
	{ z: '74', mass: null, symbol: 'W',name: 'टंग्स्टन', group: 'Transition Metals', row: 6, column: 6 },
	{ z: '75', mass: null, symbol: 'Re',name: 'रेनियम', group: 'Transition Metals', row: 6, column: 7 },
	{ z: '76', mass: null, symbol: 'Os',name: 'अस्मियम', group: 'Transition Metals', row: 6, column: 8 },
	{ z: '77', mass: null, symbol: 'Ir',name: 'इरिडियम', group: 'Transition Metals', row: 6, column: 9 },
	{ z: '78', mass: null, symbol: 'Pt',name: 'प्लाटिनम', group: 'Transition Metals', row: 6, column: 10 },
	{ z: '79', mass: null, symbol: 'Au',name: 'सोना', group: 'Transition Metals', row: 6, column: 11 },
	{ z: '80', mass: null, symbol: 'Hg',name: 'पारा', group: 'Transition Metals', row: 6, column: 12 },
	{ z: '81', mass: null, symbol: 'Tl',name: 'थैलियम', group: 'Poor Metals', row: 6, column: 13 },
	{ z: '82', mass: null, symbol: 'Pb',name: 'सीसा', group: 'Poor Metals', row: 6, column: 14 },
	{ z: '83', mass: null, symbol: 'Bi',name: 'बिस्मथ', group: 'Poor Metals', row: 6, column: 15 },
	{ z: '84', mass: null, symbol: 'Po',name: 'पोलोनियम', group: 'Poor Metals', row: 6, column: 16 },
	{ z: '85', mass: null, symbol: 'At',name: 'एस्टाटिन', group: 'Non-Metals', row: 6, column: 17 },
	{ z: '86', mass: null, symbol: 'Rn',name: 'रेडन', group: 'Nobel Gases', row: 6, column: 18 },
	{ z: '87', mass: null, symbol: 'Fr',name: 'फ्रान्सियम', group: 'Alkali Metals', row: 7, column: 1 },
	{ z: '88', mass: null, symbol: 'Ra',name: 'रेडियम', group: 'Alkali-Earth Metals', row: 7, column: 2 },
	{ z: '89-103', mass: null, symbol: 'Ac-Lr',name: 'Actinide', group: 'Actinides', row: 7, column: 3,
		items: [
			{ z: '89', mass: null, symbol: 'Ac',name: 'एक्टिनियम', group: 'Actinides', row: 1, column: 1 },
			{ z: '90', mass: null, symbol: 'Th',name: 'थोरियम', group: 'Actinides', row: 1, column: 2 },
			{ z: '91', mass: null, symbol: 'Pa',name: 'प्रोटैक्टीनियम', group: 'Actinides', row: 1, column: 3 },
			{ z: '92', mass: null, symbol: 'U',name: 'युरेनियम', group: 'Actinides', row: 1, column: 4 },
			{ z: '93', mass: null, symbol: 'Np',name: 'नेप्ट्यूनियम', group: 'Actinides', row: 1, column: 5 },
			{ z: '94', mass: null, symbol: 'Pu',name: 'प्लूटोनियम', group: 'Actinides', row: 1, column: 6 },
			{ z: '95', mass: null, symbol: 'Am',name: 'अमेरिशियम', group: 'Actinides', row: 1, column: 7 },
			{ z: '96', mass: null, symbol: 'Cm',name: 'क्यूरियम', group: 'Actinides', row: 1, column: 8 },
			{ z: '97', mass: null, symbol: 'Bk',name: 'बर्केलियम', group: 'Actinides', row: 1, column: 9 },
			{ z: '98', mass: null, symbol: 'Cf',name: 'कैलीफोर्नियम', group: 'Actinides', row: 1, column: 10 },
			{ z: '99', mass: null, symbol: 'Es',name: 'आइन्स्टाइनियम', group: 'Actinides', row: 1, column: 11 },
			{ z: '100', mass: null, symbol: 'Fm',name: 'फर्मियम', group: 'Actinides', row: 1, column: 12 },
			{ z: '101', mass: null, symbol: 'Md',name: 'मेण्डेलीवियम', group: 'Actinides', row: 1, column: 13 },
			{ z: '102', mass: null, symbol: 'No',name: 'नोबेलियम', group: 'Actinides', row: 1, column: 14 },
			{ z: '103', mass: null, symbol: 'Lr',name: 'लॉरेंशियम', group: 'Actinides', row: 1, column: 15 }
		]
	},
	{ z: '104', mass: null, symbol: 'Rf',name: 'रुथरफोर्डियम', group: 'Transition Metals', row: 7, column: 4 },
	{ z: '105', mass: null, symbol: 'Db',name: 'डब्नियम', group: 'Transition Metals', row: 7, column: 5 },
	{ z: '106', mass: null, symbol: 'Sg',name: 'सीबोर्गियम', group: 'Transition Metals', row: 7, column: 6 },
	{ z: '107', mass: null, symbol: 'Bh',name: 'बोरियम', group: 'Transition Metals', row: 7, column: 7 },
	{ z: '108', mass: null, symbol: 'Hs',name: 'हसियम', group: 'Transition Metals', row: 7, column: 8 },
	{ z: '109', mass: null, symbol: 'Mt',name: 'मेइट्नेरियम', group: 'Transition Metals', row: 7, column: 9 },
	{ z: '110', mass: null, symbol: 'Ds',name: 'डार्म्स्टेडशियम', group: 'Transition Metals', row: 7, column: 10 },
	{ z: '111', mass: null, symbol: 'Rg',name: 'रॉन्टजैनियम', group: 'Transition Metals', row: 7, column: 11 },
	{ z: '112', mass: null, symbol: 'Cn',name: 'उनउनबियम', group: 'Transition Metals', row: 7, column: 12 },
	{ z: '113', mass: null, symbol: 'Uut',name: 'उनउनट्रियम', group: 'Poor Metals', row: 7, column: 13 },
	{ z: '114', mass: null, symbol: 'Fl',name: 'Flerovium', group: 'Poor Metals', row: 7, column: 14 },
	{ z: '115', mass: null, symbol: 'Uup',name: 'उनउनपैन्शियम', group: 'Poor Metals', row: 7, column: 15 },
	{ z: '116', mass: null, symbol: 'Lv',name: 'Livermorium', group: 'Poor Metals', row: 7, column: 16 },
	{ z: '117', mass: null, symbol: 'Uus',name: 'उनउनसैप्क्षियम', group: 'Non-Metals', row: 7, column: 17 },
	{ z: '118', mass: null, symbol: 'Uuo',name: 'उनउनऑक्षियम', group: 'Nobel Gases', row: 7, column: 18 }
	]
});