Ext.define('SCE.store.PTElements', {
	extend: 'Ext.data.Store',

	requires: ['SCE.model.PTElement'],

	model: 'SCE.model.PTElement',

	storeId: 'PTElements',
	data: [
	{ z: '1', mass: null, symbol: 'H',name: '', group: '', row: 1, column: 1 },
	{ z: '2', mass: null, symbol: 'He',name: '', group: '', row: 1, column: 18 },
	{ z: '3', mass: null, symbol: 'Li',name: '', group: '', row: 2, column: 1 },
	{ z: '4', mass: null, symbol: 'Be',name: '', group: '', row: 2, column: 2 },
	{ z: '5', mass: null, symbol: 'B',name: '', group: '', row: 2, column: 13 },
	{ z: '6', mass: null, symbol: 'C',name: '', group: '', row: 2, column: 14 },
	{ z: '7', mass: null, symbol: 'N',name: '', group: '', row: 2, column: 15 },
	{ z: '8', mass: null, symbol: 'O',name: '', group: '', row: 2, column: 16 },
	{ z: '9', mass: null, symbol: 'F',name: '', group: '', row: 2, column: 17 },
	{ z: '10', mass: null, symbol: 'Ne',name: '', group: '', row: 2, column: 18 },
	{ z: '11', mass: null, symbol: 'Na',name: '', group: '', row: 3, column: 1 },
	{ z: '12', mass: null, symbol: 'Mg',name: '', group: '', row: 3, column: 2 },
	{ z: '13', mass: null, symbol: 'Al',name: '', group: '', row: 3, column: 13 },
	{ z: '14', mass: null, symbol: 'Si',name: '', group: '', row: 3, column: 14 },
	{ z: '15', mass: null, symbol: 'P',name: '', group: '', row: 3, column: 15 },
	{ z: '16', mass: null, symbol: 'S',name: '', group: '', row: 3, column: 16 },
	{ z: '17', mass: null, symbol: 'Cl',name: '', group: '', row: 3, column: 17 },
	{ z: '18', mass: null, symbol: 'Ar',name: '', group: '', row: 3, column: 18 },
	{ z: '19', mass: null, symbol: 'K',name: '', group: '', row: 4, column: 1 },
	{ z: '20', mass: null, symbol: 'Ca',name: '', group: '', row: 4, column: 2 },
	{ z: '21', mass: null, symbol: 'Sc',name: '', group: '', row: 4, column: 3 },
	{ z: '22', mass: null, symbol: 'Ti',name: '', group: '', row: 4, column: 4 },
	{ z: '23', mass: null, symbol: 'V',name: '', group: '', row: 4, column: 5 },
	{ z: '24', mass: null, symbol: 'Cr',name: '', group: '', row: 4, column: 6 },
	{ z: '25', mass: null, symbol: 'Mn',name: '', group: '', row: 4, column: 7 },
	{ z: '26', mass: null, symbol: 'Fe',name: '', group: '', row: 4, column: 8 },
	{ z: '27', mass: null, symbol: 'Co',name: '', group: '', row: 4, column: 9 },
	{ z: '28', mass: null, symbol: 'Ni',name: '', group: '', row: 4, column: 10 },
	{ z: '29', mass: null, symbol: 'Cu',name: '', group: '', row: 4, column: 11 },
	{ z: '30', mass: null, symbol: 'Zn',name: '', group: '', row: 4, column: 12 },
	{ z: '31', mass: null, symbol: 'Ga',name: '', group: '', row: 4, column: 13 },
	{ z: '32', mass: null, symbol: 'Ge',name: '', group: '', row: 4, column: 14 },
	{ z: '33', mass: null, symbol: 'As',name: '', group: '', row: 4, column: 15 },
	{ z: '34', mass: null, symbol: 'Se',name: '', group: '', row: 4, column: 16 },
	{ z: '35', mass: null, symbol: 'Br',name: '', group: '', row: 4, column: 17 },
	{ z: '36', mass: null, symbol: 'Kr',name: '', group: '', row: 4, column: 18 },
	{ z: '37', mass: null, symbol: 'Rb',name: '', group: '', row: 5, column: 1 },
	{ z: '38', mass: null, symbol: 'Sr',name: '', group: '', row: 5, column: 2 },
	{ z: '39', mass: null, symbol: 'Y',name: '', group: '', row: 5, column: 3 },
	{ z: '40', mass: null, symbol: 'Zr',name: '', group: '', row: 5, column: 4 },
	{ z: '41', mass: null, symbol: 'Nb',name: '', group: '', row: 5, column: 5 },
	{ z: '42', mass: null, symbol: 'Mo',name: '', group: '', row: 5, column: 6 },
	{ z: '43', mass: null, symbol: 'Tc',name: '', group: '', row: 5, column: 7 },
	{ z: '44', mass: null, symbol: 'Ru',name: '', group: '', row: 5, column: 8 },
	{ z: '45', mass: null, symbol: 'Rh',name: '', group: '', row: 5, column: 9 },
	{ z: '46', mass: null, symbol: 'Pd',name: '', group: '', row: 5, column: 10 },
	{ z: '47', mass: null, symbol: 'Ag',name: '', group: '', row: 5, column: 11 },
	{ z: '48', mass: null, symbol: 'Cd',name: '', group: '', row: 5, column: 12 },
	{ z: '49', mass: null, symbol: 'In',name: '', group: '', row: 5, column: 13 },
	{ z: '50', mass: null, symbol: 'Sn',name: '', group: '', row: 5, column: 14 },
	{ z: '51', mass: null, symbol: 'Sb',name: '', group: '', row: 5, column: 15 },
	{ z: '52', mass: null, symbol: 'Te',name: '', group: '', row: 5, column: 16 },
	{ z: '53', mass: null, symbol: 'I',name: '', group: '', row: 5, column: 17 },
	{ z: '54', mass: null, symbol: 'Xe',name: '', group: '', row: 5, column: 18 },
	{ z: '55', mass: null, symbol: 'Cs',name: '', group: '', row: 6, column: 1 },
	{ z: '56', mass: null, symbol: 'Ba',name: '', group: '', row: 6, column: 2 },
	{ z: '57-71', mass: null, symbol: 'La-Lu',name: 'Lanthanide', group: '', row: 6, column: 3,
		items: [
			{ z: '57', mass: null, symbol: 'La',name: '', group: '', row: 1, column: 1 },
			{ z: '58', mass: null, symbol: 'Ce',name: '', group: '', row: 1, column: 2 },
			{ z: '59', mass: null, symbol: 'Pr',name: '', group: '', row: 1, column: 3 },
			{ z: '60', mass: null, symbol: 'Nd',name: '', group: '', row: 1, column: 4 },
			{ z: '61', mass: null, symbol: 'Pm',name: '', group: '', row: 1, column: 5 },
			{ z: '62', mass: null, symbol: 'Sm',name: '', group: '', row: 1, column: 6 },
			{ z: '63', mass: null, symbol: 'Eu',name: '', group: '', row: 1, column: 7 },
			{ z: '64', mass: null, symbol: 'Gd',name: '', group: '', row: 1, column: 8 },
			{ z: '65', mass: null, symbol: 'Tb',name: '', group: '', row: 1, column: 9 },
			{ z: '66', mass: null, symbol: 'Dy',name: '', group: '', row: 1, column: 10 },
			{ z: '67', mass: null, symbol: 'Ho',name: '', group: '', row: 1, column: 11 },
			{ z: '68', mass: null, symbol: 'Er',name: '', group: '', row: 1, column: 12 },
			{ z: '69', mass: null, symbol: 'Tm',name: '', group: '', row: 1, column: 13 },
			{ z: '70', mass: null, symbol: 'Yb',name: '', group: '', row: 1, column: 14 },
			{ z: '71', mass: null, symbol: 'Lu',name: '', group: '', row: 1, column: 15 }
		]
	},
	{ z: '72', mass: null, symbol: 'Hf',name: '', group: '', row: 6, column: 4 },
	{ z: '73', mass: null, symbol: 'Ta',name: '', group: '', row: 6, column: 5 },
	{ z: '74', mass: null, symbol: 'W',name: '', group: '', row: 6, column: 6 },
	{ z: '75', mass: null, symbol: 'Re',name: '', group: '', row: 6, column: 7 },
	{ z: '76', mass: null, symbol: 'Os',name: '', group: '', row: 6, column: 8 },
	{ z: '77', mass: null, symbol: 'Ir',name: '', group: '', row: 6, column: 9 },
	{ z: '78', mass: null, symbol: 'Pt',name: '', group: '', row: 6, column: 10 },
	{ z: '79', mass: null, symbol: 'Au',name: '', group: '', row: 6, column: 11 },
	{ z: '80', mass: null, symbol: 'Hg',name: '', group: '', row: 6, column: 12 },
	{ z: '81', mass: null, symbol: 'Tl',name: '', group: '', row: 6, column: 13 },
	{ z: '82', mass: null, symbol: 'Pb',name: '', group: '', row: 6, column: 14 },
	{ z: '83', mass: null, symbol: 'Bi',name: '', group: '', row: 6, column: 15 },
	{ z: '84', mass: null, symbol: 'Po',name: '', group: '', row: 6, column: 16 },
	{ z: '85', mass: null, symbol: 'At',name: '', group: '', row: 6, column: 17 },
	{ z: '86', mass: null, symbol: 'Rn',name: '', group: '', row: 6, column: 18 },
	{ z: '87', mass: null, symbol: 'Fr',name: '', group: '', row: 7, column: 1 },
	{ z: '88', mass: null, symbol: 'Ra',name: '', group: '', row: 7, column: 2 },
	{ z: '89-103', mass: null, symbol: 'Ac-Lr',name: 'Actinide', group: '', row: 7, column: 3,
		items: [
			{ z: '89', mass: null, symbol: 'Ac',name: '', group: '', row: 1, column: 1 },
			{ z: '90', mass: null, symbol: 'Th',name: '', group: '', row: 1, column: 2 },
			{ z: '91', mass: null, symbol: 'Pa',name: '', group: '', row: 1, column: 3 },
			{ z: '92', mass: null, symbol: 'U',name: '', group: '', row: 1, column: 4 },
			{ z: '93', mass: null, symbol: 'Np',name: '', group: '', row: 1, column: 5 },
			{ z: '94', mass: null, symbol: 'Pu',name: '', group: '', row: 1, column: 6 },
			{ z: '95', mass: null, symbol: 'Am',name: '', group: '', row: 1, column: 7 },
			{ z: '96', mass: null, symbol: 'Cm',name: '', group: '', row: 1, column: 8 },
			{ z: '97', mass: null, symbol: 'Bk',name: '', group: '', row: 1, column: 9 },
			{ z: '98', mass: null, symbol: 'Cf',name: '', group: '', row: 1, column: 10 },
			{ z: '99', mass: null, symbol: 'Es',name: '', group: '', row: 1, column: 11 },
			{ z: '100', mass: null, symbol: 'Fm',name: '', group: '', row: 1, column: 12 },
			{ z: '101', mass: null, symbol: 'Md',name: '', group: '', row: 1, column: 13 },
			{ z: '102', mass: null, symbol: 'No',name: '', group: '', row: 1, column: 14 },
			{ z: '103', mass: null, symbol: 'Lr',name: '', group: '', row: 1, column: 15 }
		]
	},
	{ z: '104', mass: null, symbol: 'Rf',name: '', group: '', row: 7, column: 4 },
	{ z: '105', mass: null, symbol: 'Db',name: '', group: '', row: 7, column: 5 },
	{ z: '106', mass: null, symbol: 'Sg',name: '', group: '', row: 7, column: 6 },
	{ z: '107', mass: null, symbol: 'Bh',name: '', group: '', row: 7, column: 7 },
	{ z: '108', mass: null, symbol: 'Hs',name: '', group: '', row: 7, column: 8 },
	{ z: '109', mass: null, symbol: 'Mt',name: '', group: '', row: 7, column: 9 },
	{ z: '110', mass: null, symbol: 'Ds',name: '', group: '', row: 7, column: 10 },
	{ z: '111', mass: null, symbol: 'Rg',name: '', group: '', row: 7, column: 11 },
	{ z: '112', mass: null, symbol: 'Uub',name: '', group: '', row: 7, column: 12 },
	{ z: '113', mass: null, symbol: 'Uut',name: '', group: '', row: 7, column: 13 },
	{ z: '114', mass: null, symbol: 'Uuq',name: '', group: '', row: 7, column: 14 },
	{ z: '115', mass: null, symbol: 'Uup',name: '', group: '', row: 7, column: 15 },
	{ z: '116', mass: null, symbol: 'Uuh',name: '', group: '', row: 7, column: 16 },
	{ z: '117', mass: null, symbol: 'Uus',name: '', group: '', row: 7, column: 17 },
	{ z: '118', mass: null, symbol: 'Uuo',name: '', group: '', row: 7, column: 18 }
	]
});