Ext.define('SCE.store.PTElements', {
	extend: 'Ext.data.Store',

	requires: ['SCE.model.PTElement'],

	model: 'SCE.model.PTElement',

	storeId: 'PTElements',
	data: [
	{ z: '1', mass: null, symbol: 'H',name: 'Hydrogen', group: 'Other Non-metals', row: 1, column: 1 },
	{ z: '2', mass: null, symbol: 'He',name: 'Helium', group: 'Nobel Gases', row: 1, column: 18 },
	{ z: '3', mass: null, symbol: 'Li',name: 'Lithium', group: 'Alkali Metals', row: 2, column: 1 },
	{ z: '4', mass: null, symbol: 'Be',name: 'Beryllium', group: 'Alkali-Earth Metals', row: 2, column: 2 },
	{ z: '5', mass: null, symbol: 'B',name: 'Boron', group: 'Semi Metals', row: 2, column: 13 },
	{ z: '6', mass: null, symbol: 'C',name: 'Carbon', group: 'Non-Metals', row: 2, column: 14 },
	{ z: '7', mass: null, symbol: 'N',name: 'Nitrogen', group: 'Non-Metals', row: 2, column: 15 },
	{ z: '8', mass: null, symbol: 'O',name: 'Oxygen', group: 'Non-Metals', row: 2, column: 16 },
	{ z: '9', mass: null, symbol: 'F',name: 'Fluorine', group: 'Non-Metals', row: 2, column: 17 },
	{ z: '10', mass: null, symbol: 'Ne',name: 'Neon', group: 'Nobel Gases', row: 2, column: 18 },
	{ z: '11', mass: null, symbol: 'Na',name: 'Sodium', group: 'Alkali Metals', row: 3, column: 1 },
	{ z: '12', mass: null, symbol: 'Mg',name: 'Magnesium', group: 'Alkali-Earth Metals', row: 3, column: 2 },
	{ z: '13', mass: null, symbol: 'Al',name: 'Aluminum', group: 'Poor Metals', row: 3, column: 13 },
	{ z: '14', mass: null, symbol: 'Si',name: 'Silicon', group: 'Semi Metals', row: 3, column: 14 },
	{ z: '15', mass: null, symbol: 'P',name: 'Phosphorus', group: 'Non-Metals', row: 3, column: 15 },
	{ z: '16', mass: null, symbol: 'S',name: 'Sulfur', group: 'Non-Metals', row: 3, column: 16 },
	{ z: '17', mass: null, symbol: 'Cl',name: 'Chlorine', group: 'Non-Metals', row: 3, column: 17 },
	{ z: '18', mass: null, symbol: 'Ar',name: 'Argon', group: 'Nobel Gases', row: 3, column: 18 },
	{ z: '19', mass: null, symbol: 'K',name: 'Potassium', group: 'Alkali Metals', row: 4, column: 1 },
	{ z: '20', mass: null, symbol: 'Ca',name: 'Calcium', group: 'Alkali-Earth Metals', row: 4, column: 2 },
	{ z: '21', mass: null, symbol: 'Sc',name: 'Scandium', group: 'Transition Metals', row: 4, column: 3 },
	{ z: '22', mass: null, symbol: 'Ti',name: 'Titanium', group: 'Transition Metals', row: 4, column: 4 },
	{ z: '23', mass: null, symbol: 'V',name: 'Vanadium', group: 'Transition Metals', row: 4, column: 5 },
	{ z: '24', mass: null, symbol: 'Cr',name: 'Chromium', group: 'Transition Metals', row: 4, column: 6 },
	{ z: '25', mass: null, symbol: 'Mn',name: 'Manganese', group: 'Transition Metals', row: 4, column: 7 },
	{ z: '26', mass: null, symbol: 'Fe',name: 'Iron', group: 'Transition Metals', row: 4, column: 8 },
	{ z: '27', mass: null, symbol: 'Co',name: 'Cobalt', group: 'Transition Metals', row: 4, column: 9 },
	{ z: '28', mass: null, symbol: 'Ni',name: 'Nickel', group: 'Transition Metals', row: 4, column: 10 },
	{ z: '29', mass: null, symbol: 'Cu',name: 'Copper', group: 'Transition Metals', row: 4, column: 11 },
	{ z: '30', mass: null, symbol: 'Zn',name: 'Zinc', group: 'Transition Metals', row: 4, column: 12 },
	{ z: '31', mass: null, symbol: 'Ga',name: 'Gallium', group: 'Poor Metals', row: 4, column: 13 },
	{ z: '32', mass: null, symbol: 'Ge',name: 'Germanium', group: 'Semi Metals', row: 4, column: 14 },
	{ z: '33', mass: null, symbol: 'As',name: 'Arsenic', group: 'Semi Metals', row: 4, column: 15 },
	{ z: '34', mass: null, symbol: 'Se',name: 'Selenium', group: 'Semi Metals', row: 4, column: 16 },
	{ z: '35', mass: null, symbol: 'Br',name: 'Bromine', group: 'Non-Metals', row: 4, column: 17 },
	{ z: '36', mass: null, symbol: 'Kr',name: 'Krypton', group: 'Nobel Gases', row: 4, column: 18 },
	{ z: '37', mass: null, symbol: 'Rb',name: 'Rubidium', group: 'Alkali Metals', row: 5, column: 1 },
	{ z: '38', mass: null, symbol: 'Sr',name: 'Strontium', group: 'Alkali-Earth Metals', row: 5, column: 2 },
	{ z: '39', mass: null, symbol: 'Y',name: 'Yttrium', group: 'Transition Metals', row: 5, column: 3 },
	{ z: '40', mass: null, symbol: 'Zr',name: 'Zirconium', group: 'Transition Metals', row: 5, column: 4 },
	{ z: '41', mass: null, symbol: 'Nb',name: 'Niobium', group: 'Transition Metals', row: 5, column: 5 },
	{ z: '42', mass: null, symbol: 'Mo',name: 'Molybdenum', group: 'Transition Metals', row: 5, column: 6 },
	{ z: '43', mass: null, symbol: 'Tc',name: 'Technetium', group: 'Transition Metals', row: 5, column: 7 },
	{ z: '44', mass: null, symbol: 'Ru',name: 'Ruthenium', group: 'Transition Metals', row: 5, column: 8 },
	{ z: '45', mass: null, symbol: 'Rh',name: 'Rhodium', group: 'Transition Metals', row: 5, column: 9 },
	{ z: '46', mass: null, symbol: 'Pd',name: 'Palladium', group: 'Transition Metals', row: 5, column: 10 },
	{ z: '47', mass: null, symbol: 'Ag',name: 'Silver', group: 'Transition Metals', row: 5, column: 11 },
	{ z: '48', mass: null, symbol: 'Cd',name: 'Cadmium', group: 'Transition Metals', row: 5, column: 12 },
	{ z: '49', mass: null, symbol: 'In',name: 'Indium', group: 'Poor Metals', row: 5, column: 13 },
	{ z: '50', mass: null, symbol: 'Sn',name: 'Tin', group: 'Poor Metals', row: 5, column: 14 },
	{ z: '51', mass: null, symbol: 'Sb',name: 'Antimony', group: 'Semi Metals', row: 5, column: 15 },
	{ z: '52', mass: null, symbol: 'Te',name: 'Tellurium', group: 'Semi Metals', row: 5, column: 16 },
	{ z: '53', mass: null, symbol: 'I',name: 'Iodine', group: 'Non-Metals', row: 5, column: 17 },
	{ z: '54', mass: null, symbol: 'Xe',name: 'Xenon', group: 'Nobel Gases', row: 5, column: 18 },
	{ z: '55', mass: null, symbol: 'Cs',name: 'Cesium', group: 'Alkali Metals', row: 6, column: 1 },
	{ z: '56', mass: null, symbol: 'Ba',name: 'Barium', group: 'Alkali-Earth Metals', row: 6, column: 2 },
	{ z: '57-71', mass: null, symbol: 'La-Lu',name: 'Lanthanide', group: 'Lanthanides', row: 6, column: 3,
		items: [
			{ z: '57', mass: null, symbol: 'La',name: 'Lanthanum', group: 'Lanthanides', row: 1, column: 1 },
			{ z: '58', mass: null, symbol: 'Ce',name: 'Cerium', group: 'Lanthanides', row: 1, column: 2 },
			{ z: '59', mass: null, symbol: 'Pr',name: 'Praseodymium', group: 'Lanthanides', row: 1, column: 3 },
			{ z: '60', mass: null, symbol: 'Nd',name: 'Neodymium', group: 'Lanthanides', row: 1, column: 4 },
			{ z: '61', mass: null, symbol: 'Pm',name: 'Promethium', group: 'Lanthanides', row: 1, column: 5 },
			{ z: '62', mass: null, symbol: 'Sm',name: 'Samarium', group: 'Lanthanides', row: 1, column: 6 },
			{ z: '63', mass: null, symbol: 'Eu',name: 'Europium', group: 'Lanthanides', row: 1, column: 7 },
			{ z: '64', mass: null, symbol: 'Gd',name: 'Gadolinium', group: 'Lanthanides', row: 1, column: 8 },
			{ z: '65', mass: null, symbol: 'Tb',name: 'Terbium', group: 'Lanthanides', row: 1, column: 9 },
			{ z: '66', mass: null, symbol: 'Dy',name: 'Dysprosium', group: 'Lanthanides', row: 1, column: 10 },
			{ z: '67', mass: null, symbol: 'Ho',name: 'Holmium', group: 'Lanthanides', row: 1, column: 11 },
			{ z: '68', mass: null, symbol: 'Er',name: 'Erbium', group: 'Lanthanides', row: 1, column: 12 },
			{ z: '69', mass: null, symbol: 'Tm',name: 'Thulium', group: 'Lanthanides', row: 1, column: 13 },
			{ z: '70', mass: null, symbol: 'Yb',name: 'Ytterbium', group: 'Lanthanides', row: 1, column: 14 },
			{ z: '71', mass: null, symbol: 'Lu',name: 'Lutetium', group: 'Lanthanides', row: 1, column: 15 }
		]
	},
	{ z: '72', mass: null, symbol: 'Hf',name: 'Hafnium', group: 'Transition Metals', row: 6, column: 4 },
	{ z: '73', mass: null, symbol: 'Ta',name: 'Tantalum', group: 'Transition Metals', row: 6, column: 5 },
	{ z: '74', mass: null, symbol: 'W',name: 'Tungsten', group: 'Transition Metals', row: 6, column: 6 },
	{ z: '75', mass: null, symbol: 'Re',name: 'Rhenium', group: 'Transition Metals', row: 6, column: 7 },
	{ z: '76', mass: null, symbol: 'Os',name: 'Osmium', group: 'Transition Metals', row: 6, column: 8 },
	{ z: '77', mass: null, symbol: 'Ir',name: 'Iridium', group: 'Transition Metals', row: 6, column: 9 },
	{ z: '78', mass: null, symbol: 'Pt',name: 'Platinum', group: 'Transition Metals', row: 6, column: 10 },
	{ z: '79', mass: null, symbol: 'Au',name: 'Gold', group: 'Transition Metals', row: 6, column: 11 },
	{ z: '80', mass: null, symbol: 'Hg',name: 'Mercury', group: 'Transition Metals', row: 6, column: 12 },
	{ z: '81', mass: null, symbol: 'Tl',name: 'Thallium', group: 'Poor Metals', row: 6, column: 13 },
	{ z: '82', mass: null, symbol: 'Pb',name: 'Lead', group: 'Poor Metals', row: 6, column: 14 },
	{ z: '83', mass: null, symbol: 'Bi',name: 'Bismuth', group: 'Poor Metals', row: 6, column: 15 },
	{ z: '84', mass: null, symbol: 'Po',name: 'Polonium', group: 'Poor Metals', row: 6, column: 16 },
	{ z: '85', mass: null, symbol: 'At',name: 'Astatine', group: 'Non-Metals', row: 6, column: 17 },
	{ z: '86', mass: null, symbol: 'Rn',name: 'Radon', group: 'Nobel Gases', row: 6, column: 18 },
	{ z: '87', mass: null, symbol: 'Fr',name: 'Francium', group: 'Alkali Metals', row: 7, column: 1 },
	{ z: '88', mass: null, symbol: 'Ra',name: 'Radium', group: 'Alkali-Earth Metals', row: 7, column: 2 },
	{ z: '89-103', mass: null, symbol: 'Ac-Lr',name: 'Actinide', group: 'Actinides', row: 7, column: 3,
		items: [
			{ z: '89', mass: null, symbol: 'Ac',name: 'Actinium', group: 'Actinides', row: 1, column: 1 },
			{ z: '90', mass: null, symbol: 'Th',name: 'Thorium', group: 'Actinides', row: 1, column: 2 },
			{ z: '91', mass: null, symbol: 'Pa',name: 'Protactinium', group: 'Actinides', row: 1, column: 3 },
			{ z: '92', mass: null, symbol: 'U',name: 'Uranium', group: 'Actinides', row: 1, column: 4 },
			{ z: '93', mass: null, symbol: 'Np',name: 'Neptunium', group: 'Actinides', row: 1, column: 5 },
			{ z: '94', mass: null, symbol: 'Pu',name: 'Plutonium', group: 'Actinides', row: 1, column: 6 },
			{ z: '95', mass: null, symbol: 'Am',name: 'Americium', group: 'Actinides', row: 1, column: 7 },
			{ z: '96', mass: null, symbol: 'Cm',name: 'Curium', group: 'Actinides', row: 1, column: 8 },
			{ z: '97', mass: null, symbol: 'Bk',name: 'Berkelium', group: 'Actinides', row: 1, column: 9 },
			{ z: '98', mass: null, symbol: 'Cf',name: 'Californium', group: 'Actinides', row: 1, column: 10 },
			{ z: '99', mass: null, symbol: 'Es',name: 'Einsteinium', group: 'Actinides', row: 1, column: 11 },
			{ z: '100', mass: null, symbol: 'Fm',name: 'Fermium', group: 'Actinides', row: 1, column: 12 },
			{ z: '101', mass: null, symbol: 'Md',name: 'Mendelevium', group: 'Actinides', row: 1, column: 13 },
			{ z: '102', mass: null, symbol: 'No',name: 'Nobelium', group: 'Actinides', row: 1, column: 14 },
			{ z: '103', mass: null, symbol: 'Lr',name: 'Lawrencium', group: 'Actinides', row: 1, column: 15 }
		]
	},
	{ z: '104', mass: null, symbol: 'Rf',name: 'Rutherfordium', group: 'Transition Metals', row: 7, column: 4 },
	{ z: '105', mass: null, symbol: 'Db',name: 'Dubnium', group: 'Transition Metals', row: 7, column: 5 },
	{ z: '106', mass: null, symbol: 'Sg',name: 'Seaborgium', group: 'Transition Metals', row: 7, column: 6 },
	{ z: '107', mass: null, symbol: 'Bh',name: 'Bohrium', group: 'Transition Metals', row: 7, column: 7 },
	{ z: '108', mass: null, symbol: 'Hs',name: 'Hassium', group: 'Transition Metals', row: 7, column: 8 },
	{ z: '109', mass: null, symbol: 'Mt',name: 'Meitnerium', group: 'Transition Metals', row: 7, column: 9 },
	{ z: '110', mass: null, symbol: 'Ds',name: 'Darmstadtium', group: 'Transition Metals', row: 7, column: 10 },
	{ z: '111', mass: null, symbol: 'Rg',name: 'Roentgenium', group: 'Transition Metals', row: 7, column: 11 },
	{ z: '112', mass: null, symbol: 'Cn',name: 'Copernicium', group: 'Transition Metals', row: 7, column: 12 },
	{ z: '113', mass: null, symbol: 'Uut',name: 'Ununtrium', group: 'Poor Metals', row: 7, column: 13 },
	{ z: '114', mass: null, symbol: 'Fl',name: 'Flerovium', group: 'Poor Metals', row: 7, column: 14 },
	{ z: '115', mass: null, symbol: 'Uup',name: 'Ununpentium', group: 'Poor Metals', row: 7, column: 15 },
	{ z: '116', mass: null, symbol: 'Lv',name: 'Livermorium', group: 'Poor Metals', row: 7, column: 16 },
	{ z: '117', mass: null, symbol: 'Uus',name: 'Ununseptium', group: 'Non-Metals', row: 7, column: 17 },
	{ z: '118', mass: null, symbol: 'Uuo',name: 'Ununoctium', group: 'Nobel Gases', row: 7, column: 18 }
	]
});